name: Test Checkout Logic

on:
  workflow_dispatch:

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Properties Repository
        uses: actions/checkout@v2
        with:
          repository: <owner>/<app-properties-repo>
          path: app-properties

      - name: Print Success Message
        run: |
          echo "App Properties Repository has been checked out successfully!"
