name: Test Checkout Logic

on:
  workflow_dispatch:

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Properties Repository
        uses: actions/checkout@v2
        with:
          repository: CCI-IntegrationDeveloper/app-properties-checkout/main
          path: app-property.txt

      - name: Print Success Message
        run: |
          echo "App Properties Repository has been checked out successfully!"
